package tech.wetech.flexmodel.enumeration;

import com.fasterxml.jackson.annotation.JsonRootName;

/**
 * 兴趣
 * Generated by Flexmodel Generator
 */
@JsonRootName("user_interest")
public enum UserInterest {
    chang, tiao, rap, daLanQiu,
}
