package tech.wetech.flexmodel.enumeration;

import com.fasterxml.jackson.annotation.JsonRootName;

/**
 * 性别
 * Generated by Flexmodel Generator
 */
@JsonRootName("UserGender")
public enum UserGender {
    UNKNOWN, MALE, FEMALE,
}
