package tech.wetech.flexmodel;

import tech.wetech.flexmodel.codegen.ObjectUtils;
import tech.wetech.flexmodel.BuildItem;
import tech.wetech.flexmodel.model.EntityDefinition;
import tech.wetech.flexmodel.model.SchemaObject;
import tech.wetech.flexmodel.ImportDescribe;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by Flexmodel Generator
 */
public class System implements BuildItem {

  @Override
  public String getSchemaName() {
    return "system";
  }

  @Override
  public List<SchemaObject> getSchema() {
    List<SchemaObject> list = new ArrayList<>();
    try {
    } catch (Exception e) {
      e.printStackTrace();
    }
    return list;
  }

  @Override
  @SuppressWarnings("all")
  public List<ImportDescribe.ImportData> getData() {
    List<ImportDescribe.ImportData> list = new ArrayList<>();
    try {
    } catch (Exception e) {
      e.printStackTrace();
    }
    return list;
  }
}
