package tech.wetech.flexmodel.entity;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonRootName;
import tech.wetech.flexmodel.annotation.ModelClass;
import tech.wetech.flexmodel.annotation.ModelRelation;

import java.util.List;

/**
 * Generated by Flexmodel Generator
 */
@ModelClass("Classes")
@JsonRootName("Classes")
public class Classes {

  @ModelRelation
  @JsonProperty("students")
  private List<Student> students;

  @JsonProperty("classCode")
  private String classCode;

  @JsonProperty("id")
  private Long id;

  @JsonProperty("className")
  private String className;

  @JsonProperty("students")
  public List<Student> getStudents() {
    return students;
  }

  public void setStudents(List<Student> students) {
    this.students = students;
  }

  @JsonProperty("classCode")
  public String getClassCode() {
    return classCode;
  }

  public void setClassCode(String classCode) {
    this.classCode = classCode;
  }

  @JsonProperty("id")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  @JsonProperty("className")
  public String getClassName() {
    return className;
  }

  public void setClassName(String className) {
    this.className = className;
  }

  @Override
  public String toString() {
    return this.getClass().getSimpleName() + "<" + getId() + ">";
  }

  @Override
  public boolean equals(Object obj) {
    if (this.getId() != null && obj instanceof Classes) {
      return this.getId().equals(((Classes) obj).getId());
    }
    return super.equals(obj);
  }

}
