package tech.wetech.flexmodel.entity;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonRootName;

/**
 * Generated by Flexmodel Generator
 */
@JsonRootName("StudentDetail")
public class StudentDetail {

  @JsonProperty("id")
  private Long id;

  @JsonProperty("studentId")
  private Long studentId;

  @JsonProperty("description")
  private String description;

  /**
   * 学生
   */
  @JsonProperty("student")
  private Student student;

  @JsonProperty("id")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  @JsonProperty("studentId")
  public Long getStudentId() {
    return studentId;
  }

  public void setStudentId(Long studentId) {
    this.studentId = studentId;
  }

  @JsonProperty("description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  @JsonProperty("student")
  public Student getStudent() {
    return student;
  }

  public void setStudent(Student student) {
    this.student = student;
  }

  @Override
  public String toString() {
    return this.getClass().getSimpleName() + "<" + getId() + ">";
  }

  @Override
  public boolean equals(Object obj) {
    if (this.getId() != null && obj instanceof StudentDetail) {
      return this.getId().equals(((StudentDetail) obj).getId());
    }
    return super.equals(obj);
  }

}
