package tech.wetech.flexmodel.test.entity;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonRootName;
import tech.wetech.flexmodel.test.enumeration.UserGender;
import tech.wetech.flexmodel.test.enumeration.UserInterest;

import java.util.Set;

/**
 * Generated by Flexmodel Generator
 */
@JsonRootName("Student")
public class Student {

  @JsonProperty("studentDetail")
  private StudentDetail studentDetail;

  @JsonProperty("age")
  private Integer age;

  @JsonProperty("id")
  private Long id;

  /**
   * 班级
   */
  @JsonProperty("studentClass")
  private Classes studentClass;

  @JsonProperty("interest")
  private Set<UserInterest> interest;

  @JsonProperty("classId")
  private Long classId;

  @JsonProperty("studentName")
  private String studentName;

  @JsonProperty("gender")
  private UserGender gender;

  @JsonProperty("studentDetail")
  public StudentDetail getStudentDetail() {
    return studentDetail;
  }

  public void setStudentDetail(StudentDetail studentDetail) {
    this.studentDetail = studentDetail;
  }

  @JsonProperty("age")
  public Integer getAge() {
    return age;
  }

  public void setAge(Integer age) {
    this.age = age;
  }

  @JsonProperty("id")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  @JsonProperty("studentClass")
  public Classes getStudentClass() {
    return studentClass;
  }

  public void setStudentClass(Classes studentClass) {
    this.studentClass = studentClass;
  }

  @JsonProperty("interest")
  public Set<UserInterest> getInterest() {
    return interest;
  }

  public void setInterest(Set<UserInterest> interest) {
    this.interest = interest;
  }

  @JsonProperty("classId")
  public Long getClassId() {
    return classId;
  }

  public void setClassId(Long classId) {
    this.classId = classId;
  }

  @JsonProperty("studentName")
  public String getStudentName() {
    return studentName;
  }

  public void setStudentName(String studentName) {
    this.studentName = studentName;
  }

  @JsonProperty("gender")
  public UserGender getGender() {
    return gender;
  }

  public void setGender(UserGender gender) {
    this.gender = gender;
  }

  @Override
  public String toString() {
    return this.getClass().getSimpleName() + "<" + getId() + ">";
  }

  @Override
  public boolean equals(Object obj) {
    if (this.getId() != null && obj instanceof Student) {
      return this.getId().equals(((Student) obj).getId());
    }
    return super.equals(obj);
  }

}
