package tech.wetech.flexmodel.codegen
/**
 * PojoGenerator Class
 * Generates Java POJOs based on the provided model definitions.
 *
 * Author: cjbi
 */
class DSLGenerator extends AbstractGenerator {

  /**
   * Writes the Java class content to the GroovyPrintWriter.
   *
   * @param out Print writer to output the Java class code.
   * @param className The name of the class.
   * @param context The generation context with model details.
   */
  def generate(PrintWriter out, GenerationContext context) {
    def modelClass = context.modelClass
    def className = modelClass.shortClassName
    def fields = modelClass.allFields
    String rootPackage = context.getVariable("rootPackage");
    // Write package statement
    out.println "package ${rootPackage}.dsl;"
    out.println ""

    // Write import statements
    if (modelClass.imports) {
      modelClass.imports.each { importStatement ->
        out.println "import ${importStatement};"
      }
      out.println ""
    }

    out.println ""
    out.println "import tech.wetech.flexmodel.dsl.FieldExpression;"
    out.println ""

    // Write class-level comments
    out.println "/**"
    if (modelClass.comment) {
      out.println " * ${modelClass.comment}"
    }
    out.println " * Generated by Flexmodel Generator"
    out.println " */"

    // Write class declaration
    out.println "public class ${className}DSL {"

    // Write field declarations
    fields.findAll { f -> !f.isRelationField() }.each { field ->
      out.println ""
      if (field.comment) {
        out.println "  /**"
        out.println "   * ${field.comment}"
        out.println "   */"
      }
      out.println "  public final FieldExpression<${field.shortTypeName}> ${field.fieldName} = new FieldExpression<>(\"${field.originalField.name}\");"
    }

    out.println ""
    // Close class
    out.println "}"
  }

}
