package tech.wetech.flexmodel.codegen


import groovy.util.logging.Log

/**
 * @author cjbi
 */
@Log
class EnumGenerator extends AbstractGenerator {

  @Override
  def generate(PrintWriter out, GenerationContext context) {
    def enumClass = context.enumClass;
    def className = enumClass.shortClassName
    def elements = enumClass.elements

    // Write package statement
    out.println "package ${enumClass.packageName};"
    out.println ""
    out.println "import com.fasterxml.jackson.annotation.JsonRootName;"
    out.println ""
    // Write class-level comments
    out.println "/**"
    if (enumClass.comment) {
      out.println " * ${enumClass.comment}"
    }
    out.println " * Generated by Flexmodel Generator"
    out.println " */"

    // Write class declaration
    out.println "@JsonRootName(\"${enumClass.originalEnum.name}\")"
    out.println "public enum ${className} {"
    out.print "    "
    // Write field declarations
    elements.each { element ->
      out.print "${element}, "
    }

    out.println ""
    // Close class
    out.println "}"
  }

}
