package tech.wetech.flexmodel.core.codegen


import groovy.util.logging.Log
import tech.wetech.flexmodel.codegen.GenerationContext

import java.nio.file.Path

/**
 * @author cjbi
 */
@Log
class EnumGenerator extends AbstractGenerator {

  @Override
  String getTargetFile(GenerationContext context, String targetDirectory) {
    return Path.of(targetDirectory, "enumeration", context.enumClass.getShortClassName() + ".java").toString()
  }

  @Override
  void writeEnum(PrintWriter out, GenerationContext context) {
    def enumClass = context.enumClass;
    def className = enumClass.shortClassName
    def elements = enumClass.elements

    // Write package statement
    out.println "package ${enumClass.packageName};"
    out.println ""
    // Write class-level comments
    out.println "/**"
    if (enumClass.comment) {
      out.println " * ${enumClass.comment}"
    }
    out.println " * Generated by Flexmodel Generator"
    out.println " */"

    // Write class declaration
    out.println "public enum ${className} {"
    out.print "    "
    // Write field declarations
    elements.each { element ->
      out.print "${element}, "
    }

    out.println ""
    // Close class
    out.println "}"
  }

}
